controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - back_left_joint
      - bogie_left_front_wheel_joint
      - bogie_left_back_wheel_joint
      - back_right_joint
      - bogie_right_front_wheel_joint
      - bogie_right_back_wheel_joint
