controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - back_left_wheel_joint
      - bogie_left_wheel_front_joint
      - bogie_left_wheel_back_joint
      - back_right_wheel_joint
      - bogie_right_wheel_front_joint
      - bogie_right_wheel_back_joint
