rover:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  `   

  # Position Controllers ---------------------------------------
  # Differential Drive Controller
  diff_drive_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["front_left_wheel_joint", "middle_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "middle_right_wheel_joint", "rear_right_wheel_joint"]
    publish_rate: 50
    wheel_separation: 0.16 #160mm
    wheel_radius: 0.05 #50mm
