controller_manager:
  ros__parameters:
    update_rate: 100.0

      joint_state_controller:
        type: joint_state_controller/JointStateController

      diff_drive_base_controller:
        type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_1_joint", "left_wheel_2_joint", "left_wheel_3_joint"]
    right_wheel_names: ["right_wheel_1_joint", "right_wheel_2_joint", "right_wheel_3_joint"]

    wheel_seperation: 0.160
    wheel_radius: 0.05

    linear_velocity: 0.5
    angular_velocity: 0.0